const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript'),path=require('path');
function carregar(p){const api={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:api,require:n=>carregar(path.resolve(path.dirname(p),n+'.ts'))});return api;}
const precos=carregar('src/utils/atualizarPrecosOrcamento.ts'),revisoes=carregar('src/utils/revisoesOrcamento.ts');
const material={id:'m1',descricao:'VIDRO 1000x2000 INCOLOR 08mm TEMPERADO',unidade:'m2',qtd:2,valorUnitario:100};
const projeto={id:'p1',projeto:'Box',materiais:[material],valorTotal:180};
const catalogo=[{id:'v1',vidro:true,descricao:'Incolor 08mm Temperado',preco:150}];
test('consulta não modifica orçamento e reconhece vidro com medidas',()=>{const original=JSON.stringify(projeto);const l=precos.compararPrecosOrcamento([projeto],[],catalogo);assert.equal(l[0].atual,150);assert.equal(JSON.stringify(projeto),original);});
test('aplica apenas seleção e preserva desconto monetário',()=>{const l=precos.compararPrecosOrcamento([projeto],[],catalogo);assert.equal(precos.aplicarPrecosOrcamento([projeto],[],l,new Set()).projetos[0].valorTotal,180);const p=precos.aplicarPrecosOrcamento([projeto],[],l,new Set([l[0].chave])).projetos[0];assert.equal(p.valorTotal,280);assert.equal(p.materiais[0].valorUnitario,150);assert.equal(material.valorUnitario,100);});
test('cadastro ambíguo ou sem preço não altera preço anterior',()=>{for(const c of [[...catalogo,...catalogo],[],[{...catalogo[0],preco:null}]]){const l=precos.compararPrecosOrcamento([projeto],[],c);assert.equal(l[0].atual,null);assert.equal(precos.aplicarPrecosOrcamento([projeto],[],l,new Set([l[0].chave])).projetos[0].valorTotal,180);}});
test('não confunde vidro com outra espessura ou tipo',()=>{for(const descricao of ['Incolor 10mm Temperado','Incolor 08mm Laminado'])assert.equal(precos.compararPrecosOrcamento([projeto],[],[{vidro:true,descricao,preco:900}])[0].atual,null);});
test('perfil exige mesma cor e reconhece separadores',()=>{const p={...projeto,materiais:[{...material,descricao:'TR032 - TUBO | PRETO',unidade:'barra'}]};assert.equal(precos.compararPrecosOrcamento([p],[],[{descricao:'TR032 - Tubo - Preto',preco:50}])[0].atual,50);assert.equal(precos.compararPrecosOrcamento([p],[],[{descricao:'TR032 - Tubo - Branco',preco:50}])[0].atual,null);});
test('vidro avulso preserva 7%, serviços, desconto e área cobrada',()=>{const p={id:'p',valorTotal:438,materiais:[{...material,qtd:4,valorUnitario:109.5}],vidrosAvulsos:[{precoVidroM2:107,valorTotal:438}],itensOriginais:[{vidro_id:'v1',descricao:'Incolor',medidaCalc:'1000 x 2000 mm',qtd:2,precoVidroM2:107,valorUnitario:229,total:438,totalOriginal:458,observacaoPreco:'Acrescimo de 7% por medida acima de 2800mm'}]};const l=precos.compararPrecosOrcamento([p],[],catalogo);assert.equal(l[0].atual,160.5);const r=precos.aplicarPrecosOrcamento([p],[],l,new Set([l[0].chave])).projetos[0];assert.equal(r.valorTotal,652);assert.equal(r.itensOriginais[0].totalOriginal,672);assert.equal(r.itensOriginais[0].valorUnitario,336);assert.equal(r.vidrosAvulsos[0].valorTotal,652);assert.equal(r.vidrosAvulsos[0].areaCobradaM2,4);assert.equal(r.materiais[0].valorUnitario*4,652);assert.equal(p.valorTotal,438);});
test('vidro antigo sem memória é sinalizado e mantido',()=>{const p={...projeto,vidrosAvulsos:[{valorTotal:180}],itensOriginais:[{descricao:'Incolor',precoVidroM2:100}]};assert.equal(precos.compararPrecosOrcamento([p],[],catalogo)[0].atual,null);});
test('material avulso atualiza sem mudar quantidade',()=>{const m={...material,descricao:'KIT BOX | BRANCO',unidade:'und',qtd:3};const l=precos.compararPrecosOrcamento([], [m], [{descricao:'K1 - Kit Box - Branco',alternativas:['Kit Box - Branco'],preco:120}]);assert.equal(precos.aplicarPrecosOrcamento([], [m],l,new Set([l[0].chave])).avulsos[0].valorUnitario,120);});
test('revisão preserva snapshot independente e sem histórico recursivo',()=>{const old={numero_formatado:'000123',valor_total:180,itens:{projetos:[projeto]}};const r=revisoes.registrarRevisaoOrcamento(old,'2026-10-03T12:00:00Z');assert.equal(r.revisaoAtual,2);assert.equal(r.revisoesPrecos[0].numero,'000123');const r2=revisoes.registrarRevisaoOrcamento({...old,itens:{...old.itens,...r}},'2026-10-04T12:00:00Z');assert.equal(r2.revisoesPrecos.length,2);assert.equal(r2.revisoesPrecos[1].itens.revisoesPrecos,undefined);old.itens.projetos[0]={...projeto,valorTotal:999};assert.equal(r.revisoesPrecos[0].itens.projetos[0].valorTotal,180);});
test('PDF da revisão inclui materiais avulsos antigos e usa snapshot completo novo',()=>{const r={numero:'123',cliente:'Ana',itens:{projetosPdf:[{id:'p'}],materiaisAvulsos:[material]}};const itens=revisoes.projetosPdfDaRevisao(r);assert.equal(itens.length,2);assert.equal(itens[1].valorTotal,200);r.itens.documentoPdfCompleto=itens;assert.equal(revisoes.projetosPdfDaRevisao(r).length,2);});

const historicos=carregar('src/utils/preservarPrecosOrcamento.ts');
test('reabrir cálculo preserva preço antigo mesmo com novo preço no catálogo',()=>{const antigos=[{...material,valorUnitario:100}];const calculados=[{...material,descricao:'VIDRO 1500x2000 INCOLOR 08mm TEMPERADO',qtd:3,valorUnitario:150}];const r=historicos.preservarPrecosOrcamento(antigos,calculados,true);assert.equal(r[0].valorUnitario,100);assert.equal(r[0].qtd,3);assert.equal(historicos.preservarPrecosOrcamento(antigos,calculados,false)[0].valorUnitario,150);});
test('trocar material durante edição usa preço do novo material',()=>{const novo={...material,descricao:'VIDRO 1000x2000 VERDE 08mm TEMPERADO',valorUnitario:210};assert.equal(historicos.preservarPrecosOrcamento([material],[novo],true)[0].valorUnitario,210);});
test('reabrir após atualização explícita preserva preço atualizado',()=>{const salvo={...material,valorUnitario:150};const recalculo={...material,valorUnitario:200};assert.equal(historicos.preservarPrecosOrcamento([salvo],[recalculo],true)[0].valorUnitario,150);});

test('espelho preserva acabamento percentual e desconto ao atualizar vidro',()=>{const calc=carregar('src/utils/calculoEspelhos.ts');const base=calc.calcularEspelho({largura:1000,altura:1000,quantidade:1,precoVidroM2:100,acabamento:{id:'a',nome:'Bisotê',tipo_visual:'simples',tipo_calculo:'porcentagem',porcentagem_aumento:10}});const p={id:'esp',valorTotal:100,materiais:[{...material,qtd:1,valorUnitario:100}],espelhoItens:[{vidroId:'v1',descricao:'Espelho',precoVidroM2:100,m2:1,total:100,memoriaCalculo:base.memoriaCalculo}],vidrosAvulsos:[{precoVidroM2:100,valorTotal:100}]};const l=precos.compararPrecosOrcamento([p],[],catalogo);assert.equal(l[0].atual,150);const r=precos.aplicarPrecosOrcamento([p],[],l,new Set([l[0].chave])).projetos[0];assert.equal(r.valorTotal,155);assert.equal(r.espelhoItens[0].memoriaCalculo.valorAcabamento,15);assert.equal(r.espelhoItens[0].memoriaCalculo.total,165);assert.equal(r.vidrosAvulsos[0].valorTotal,155);assert.equal(p.valorTotal,100);});
