const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
const transpile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
function api(search='',listener){const output={},storage=new Map();const window={location:{search},localStorage:{setItem:(k,v)=>storage.set(k,v)},dispatchEvent:e=>{if(!listener)return true;listener(e.detail);return false;}};vm.runInNewContext(transpile(fs.readFileSync('src/utils/envioOrcamento.ts','utf8')),{exports:output,window,URLSearchParams,CustomEvent:class{constructor(type,options){Object.assign(this,options);}}});return {...output,storage};}
test('cancelar PDF+ não altera item nem rascunho',async()=>{const a=api('',p=>p.concluir(null)),item={cliente:'Ana',obra:'Original'};assert.equal(await a.confirmarEnvioOrcamento([item]),false);assert.equal(item.obra,'Original');assert.equal(a.storage.size,0);});
test('edição de item e lote não abre nova escolha',async()=>{for(const query of ['?centralItem=1','?loteId=2']){const a=api(query,()=>assert.fail('não deveria perguntar'));assert.equal(await a.confirmarEnvioOrcamento([{cliente:'Ana'}]),true);}});
test('confirmação transfere obra para todos os itens do lote',async()=>{const a=api('',p=>p.concluir({obra:'Fachada'})),itens=[{cliente:'Ana'},{cliente:'Ana'}];assert.equal(await a.confirmarEnvioOrcamento(itens),true);assert.ok(itens.every(i=>i.obra==='Fachada'));});
test('clique repetido enquanto janela está aberta não duplica envio',async()=>{let pedido;const a=api('',p=>pedido=p);const primeiro=a.confirmarEnvioOrcamento([{cliente:'Ana'}]);assert.equal(await a.confirmarEnvioOrcamento([{cliente:'Ana'}]),false);pedido.concluir({});assert.equal(await primeiro,true);});
const source=fs.readFileSync('src/context/OrcamentoContext.tsx','utf8');const ast=ts.createSourceFile('context.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let handler;function walk(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='escolherEnvio')handler=n.initializer.getText(ast);ts.forEachChild(n,walk);}walk(ast);
function provider(itensExistentes=[]){let result,active,error;const storage=new Map([['glasscode:central-impressao:composicao',JSON.stringify(itensExistentes)]]);const pedido={itens:[{cliente:'Ana'}],concluir:r=>result=r};const scope={pedido,iniciandoPdf:false,storageKey:'conta-1',empresaId:'empresa-1',ativo:null,pedidoRef:{current:pedido},obra:'Obra A',PREFIXO:'glasscode:central-impressao:',crypto:{randomUUID:()=> 'orc-1'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setIniciandoPdf(){},setPedido(){},setErro:e=>error=e,setAtivo:a=>active=a,supabase:{from:()=>({select:()=>({eq:()=>({eq:()=>({limit:async()=>({data:[{id:'cliente-1',nome:'Ana'}]})})})})})}};const run=vm.runInNewContext(transpile('const escolher = '+handler+';')+'\nescolher',scope);return {run,storage,get result(){return result},get active(){return active},get error(){return error}};}
test('somente este item não mantém cliente ativo',async()=>{const p=provider();await p.run(false);assert.equal(p.active,undefined);assert.equal(p.result.obra,'Obra A');assert.equal(p.storage.has('conta-1'),false);});
test('vários itens mantém cliente e obra na conta atual',async()=>{const p=provider();await p.run(true);assert.equal(p.active.cliente.id,'cliente-1');assert.equal(JSON.parse(p.storage.get('conta-1')).obra,'Obra A');assert.equal(p.result.obra,'Obra A');});
test('novo orçamento não mistura composição de outro cliente',async()=>{const p=provider([{cliente:'Outro'}]);await p.run(true);assert.equal(p.active,undefined);assert.equal(p.result,undefined);assert.match(p.error,/outro cliente/);});
