const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
const transpile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const scroll={};vm.runInNewContext(transpile('src/utils/opcaoVisivel.ts'),{exports:scroll});
test('rolagem acompanha opção abaixo, acima e mantém opção visível',()=>{const lista={scrollTop:50,getBoundingClientRect:()=>({top:100,bottom:300})};for(const [top,bottom,esperado] of [[290,330,80],[80,110,60],[150,180,60]]){scroll.revelarOpcaoAtiva({parentElement:lista,getBoundingClientRect:()=>({top,bottom})},true);assert.equal(lista.scrollTop,esperado);}});
function montar(){let state=[],cursor=0,selecionado=null;const api={},jsx=(type,props)=>({type,props});const react={useState:init=>{const i=cursor++;if(!(i in state))state[i]=init;return [state[i],v=>state[i]=v];},useEffect:()=>{},useId:()=> 'busca',useRef:()=>({current:null})};vm.runInNewContext(transpile('src/components/BuscaMaterialInput.tsx'),{exports:api,document:{body:{}},require:n=>n==='react'?react:n==='react/jsx-runtime'?{jsx,jsxs:jsx,Fragment:'fragment'}:n==='react-dom'?{createPortal:x=>x}:scroll});const itens=Array.from({length:30},(_,i)=>({id:String(i),descricao:'PERFIL '+i,tipo:'perfil'}));let item={id:'novo',descricao:''};const render=()=>{cursor=0;return api.default({item,itensCatalogo:itens,atualizarMaterial:(_id,_campo,v)=>item.descricao=v,selecionarItemCatalogo:(_id,c)=>selecionado=c});};return {render,selecionado:()=>selecionado,descricao:()=>item.descricao};}
test('busca permite navegar além dos primeiros dez materiais e selecionar com Enter',()=>{const h=montar();h.render().props.children[0].props.onFocus();for(let i=0;i<20;i++)h.render().props.children[0].props.onKeyDown({key:'ArrowDown',preventDefault(){}});const input=h.render().props.children[0];assert.equal(input.props['aria-activedescendant'],'busca-20');input.props.onKeyDown({key:'Enter',preventDefault(){}});assert.equal(h.selecionado().id,'20');assert.equal(h.render().props.children[0].props['aria-expanded'],false);});
test('Tab fecha lista sem selecionar nem impedir navegação',()=>{const h=montar();h.render().props.children[0].props.onFocus();h.render().props.children[0].props.onKeyDown({key:'Tab',preventDefault(){throw Error('Tab bloqueado');}});assert.equal(h.selecionado(),null);assert.equal(h.render().props.children[0].props['aria-expanded'],false);});

test('digitação mantém pesquisa aberta sem reordenar material do orçamento',()=>{const h=montar();h.render().props.children[0].props.onFocus();for(const texto of ['P','PE','PERFIL 2']){h.render().props.children[0].props.onChange({target:{value:texto}});const input=h.render().props.children[0];assert.equal(input.props.value,texto);assert.equal(input.props['aria-expanded'],true);assert.equal(h.descricao(),'');}h.render().props.children[0].props.onBlur();assert.equal(h.descricao(),'PERFIL 2');});
