const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {PGlite}=require(process.env.PGLITE_MODULE);
test('retenção: autorização, isolamento, proteção, lixeira, restauração e expiração',async()=>{
 const db=new PGlite();
 const owner='00000000-0000-0000-0000-000000000001', admin='00000000-0000-0000-0000-000000000002', outsider='00000000-0000-0000-0000-000000000003';
 const a='10000000-0000-0000-0000-000000000001',b='10000000-0000-0000-0000-000000000002';
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table public.empresas(id uuid primary key);create table public.perfis_usuarios(id uuid,empresa_id uuid);
 create function public.gc_proprietaria() returns boolean language sql as $$select auth.uid()='${owner}'::uuid$$;
 create table public.orcamentos(id uuid primary key,empresa_id uuid,numero_formatado text,cliente_nome text,valor_total numeric,created_at timestamptz default now(),status text,obra_referencia text,obra_id uuid,dados jsonb);
 insert into auth.users values('${owner}','owner@test'),('${admin}','admin@test'),('${outsider}','other@test');insert into empresas values('${a}'),('${b}');insert into perfis_usuarios values('${owner}','${a}'),('${admin}','${a}'),('${outsider}','${b}');`);
 await db.exec(fs.readFileSync('database/orcamentos_armazenamento.sql','utf8'));
 await db.exec(fs.readFileSync('database/orcamentos_limpeza_periodo.sql','utf8'));
 const login=async uid=>db.query("select set_config('test.uid',$1,false)",[uid]);
 const rpc=async(action,params={})=>(await db.query('select public.gc_armazenamento($1,$2,$3,$4,$5) r',[action,params.days??null,params.before??null,params.ids??null,params.email??null])).rows[0].r;
 await login(admin);assert.equal((await rpc('consultar')).autorizado,false);await assert.rejects(rpc('configurar',{days:30}));
 await login(owner);await rpc('autorizar',{email:'admin@test'});await login(admin);assert.equal((await rpc('consultar')).autorizado,true);await rpc('configurar',{days:30});await assert.rejects(rpc('configurar',{days:1}));
 for(let i=1;i<=5;i++)await db.query('insert into orcamentos(id,empresa_id,status,obra_referencia) values($1,$2,$3,$4)',[`20000000-0000-0000-0000-00000000000${i}`,i===5?b:a,i===2?'aprovado':'pendente',i===3?'Obra teste':null]);
 await db.exec("update orcamentos set obra_id='90000000-0000-0000-0000-000000000001' where obra_referencia='Obra teste'");
 await db.exec("alter table orcamentos disable trigger gc_orcamento_data;update orcamentos set gc_alterado_em=now()-interval '60 days';alter table orcamentos enable trigger gc_orcamento_data;");
 const before=new Date().toISOString();let preview=await rpc('previa',{before});assert.equal(preview.length,2);
 const ids=preview.map(i=>i.id);assert.equal((await rpc('limpar',{before,ids})).quantidade,2);assert.equal((await rpc('lixeira')).length,2);
 await login(outsider);await assert.rejects(rpc('lixeira'));await assert.rejects(rpc('restaurar',{ids}));
 await login(admin);assert.equal((await rpc('restaurar',{ids:[ids[0]]})).quantidade,1);assert.equal((await rpc('previa',{before})).length,0);
 await db.exec("select glasscode_private.executar_retencao()");assert.equal((await rpc('lixeira')).length,1);
 await db.exec("update orcamentos set gc_excluido_em=now()-interval '31 days' where gc_excluido_em is not null;");assert.equal((await rpc('restaurar',{ids})).quantidade,0);await db.exec('select glasscode_private.executar_retencao()');assert.equal((await rpc('lixeira')).length,0);
 assert.equal((await db.query('select count(*)::int n from orcamentos')).rows[0].n,4);
 await login(owner);await rpc('revogar',{email:'admin@test'});await login(admin);assert.equal((await rpc('consultar')).autorizado,false);
 await assert.rejects(db.exec("delete from public.orcamentos"));
 await db.exec("grant usage on schema auth,public to authenticated;grant select,update,delete on orcamentos to authenticated;grant select on perfis_usuarios to authenticated;create policy empresa_leitura on orcamentos for all to authenticated using(empresa_id=(select empresa_id from perfis_usuarios where id=auth.uid())) with check(empresa_id=(select empresa_id from perfis_usuarios where id=auth.uid()));");
 await login(owner);await rpc('autorizar',{email:'admin@test'});await rpc('autorizar',{email:'other@test'});
 await login(outsider);assert.equal((await rpc('limpar',{before:new Date().toISOString(),ids:[ids[0]]})).quantidade,0);
 await db.exec('set role authenticated');
 assert.equal((await db.query('select count(*)::int n from orcamentos')).rows[0].n,1);
 assert.equal((await db.query('delete from orcamentos returning id')).rows.length,0);
 await assert.rejects(db.exec('select glasscode_private.executar_retencao()'));
 await db.exec('reset role');
 await login(admin);
 for(let i=1;i<=3;i++) await db.query("insert into orcamentos(id,empresa_id,created_at,status) values($1,$2,$3,'pendente')",['30000000-0000-0000-0000-00000000000'+i,a,['2026-01-01T03:00:00Z','2026-01-02T02:59:59Z','2026-01-02T03:00:00Z'][i-1]]);
 const periodo=async(ids=null,rev=null)=>(await db.query('select public.gc_limpar_orcamentos_periodo($1,$2,$3,$4) r',['2026-01-01T03:00:00Z','2026-01-02T03:00:00Z',ids,rev])).rows[0].r;
 const pre=await periodo();assert.equal(pre.itens.length,2,'inclui início e fim do dia, exclui dia seguinte');
 await db.query('update orcamentos set cliente_nome=$1 where id=$2',['Editado após prévia',pre.itens[0].id]);
 assert.equal((await periodo(pre.itens.map(i=>i.id),pre.revisado_em)).quantidade,1,'preserva alterado depois da prévia');
 await assert.rejects(db.query("select public.gc_limpar_orcamentos_periodo('2026-01-03','2026-01-01')"));
 await login(outsider);assert.equal((await periodo(pre.itens.map(i=>i.id),pre.revisado_em)).quantidade,0);
 // Regressão: referências antigas não são obras vinculadas; só o carimbo da instalação é corrigido.
 const legadoEmpresa='b2ac500e-99be-4b50-a96b-39db8989dfd7';
 await db.exec("alter table orcamentos add column excluir_em timestamptz;alter table orcamentos add column updated_at timestamptz;");
 await db.query('insert into empresas values($1)',[legadoEmpresa]);
 await db.query('insert into glasscode_private.retencao_config(empresa_id,dias) values($1,90)',[legadoEmpresa]);
 for(let i=1;i<=4;i++) await db.query("insert into orcamentos(id,empresa_id,created_at,excluir_em,obra_referencia,status) values($1,$2,'2026-03-01','2026-05-30','Referência antiga',$3)",['40000000-0000-0000-0000-00000000000'+i,i===4?b:legadoEmpresa,i===3?'aprovado':'']);
 await db.exec("alter table orcamentos disable trigger gc_orcamento_data;update orcamentos set gc_alterado_em='2026-09-27T12:31:38.47709Z' where id::text like '40000000%';update orcamentos set gc_alterado_em='2026-09-28' where id='40000000-0000-0000-0000-000000000002';alter table orcamentos enable trigger gc_orcamento_data;");
 await db.exec(fs.readFileSync('database/orcamentos_corrigir_legado_90dias.sql','utf8'));
 const leg=(await db.query("select id,gc_alterado_em::text data,glasscode_private.orcamento_protegido(to_jsonb(o)) protegido from orcamentos o where id::text like '40000000%' order by id")).rows;
 assert.ok(leg[0].data.startsWith('2026-03-01'));assert.equal(leg[0].protegido,false);
 assert.ok(leg[1].data.startsWith('2026-09-28'),'não altera orçamento editado');
 assert.equal(leg[2].protegido,true,'preserva aprovados');
 assert.ok(leg[3].data.startsWith('2026-09-27'),'não migra datas de outra empresa');
 await db.exec(fs.readFileSync('database/orcamentos_corrigir_legado_90dias.sql','utf8'));
 assert.equal((await db.query("select count(*)::int n from orcamentos where id::text like '40000000%'")).rows[0].n,4,'migração repetida não apaga registros');
 await db.close();
});
