// Execute com PGLITE_MODULE apontando para @electric-sql/pglite instalado fora da aplicação.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const owner = '10000000-0000-4000-8000-000000000001';
const user = '10000000-0000-4000-8000-000000000002';
const company = '20000000-0000-4000-8000-000000000002';
const migration = fs.readFileSync(path.join(__dirname, '../database/painel_plataforma.sql'), 'utf8');

test('permissões reais do painel, bloqueio RLS, reativação e histórico', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated;
      create schema auth;
      create table auth.users(id uuid primary key, email text, email_confirmed_at timestamptz, created_at timestamptz default now(), last_sign_in_at timestamptz);
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema auth to authenticated;
      create table public.empresas(id uuid primary key, nome text);
      create table public.perfis_usuarios(id uuid primary key references auth.users(id), empresa_id uuid references public.empresas(id));
      create table public.orcamentos(id integer primary key, empresa_id uuid references public.empresas(id));
      create table public.projeto_templates(id integer primary key, empresa_id uuid references public.empresas(id));
      create policy "Templates por empresa - select" on projeto_templates for select to public using (empresa_id = auth.uid());
      create table public.tipologias(id uuid primary key, empresa_id uuid references public.empresas(id));
      create table public.tipologias_ferragens(id uuid primary key, tipologia_id uuid references public.tipologias(id));
      create table public.tipologias_perfis(id uuid primary key, tipologia_id uuid references public.tipologias(id));
      create table public.tipologias_vidros(id uuid primary key, tipologia_id uuid references public.tipologias(id));
      create table public.usuarios(id uuid primary key references auth.users(id), empresa_id uuid references public.empresas(id), role text);
      create table public.ferragens_cores(id bigint primary key);
      create table public.materiais(id uuid primary key);
      create table public.medidas(id bigint primary key);
      insert into auth.users(id,email,email_confirmed_at) values ('${owner}','engenheiraceo@gmail.com',now()),('${user}','cliente@example.com',now());
      insert into empresas values ('20000000-0000-4000-8000-000000000001','Glass Code'),('${company}','Empresa cliente');
      insert into perfis_usuarios values ('${owner}','20000000-0000-4000-8000-000000000001'),('${user}','${company}');
      insert into orcamentos values (1,'${company}');
      insert into projeto_templates values (1,'${company}'),(2,'20000000-0000-4000-8000-000000000001'),(3,null);
      alter table empresas enable row level security;
      alter table perfis_usuarios enable row level security;
      alter table orcamentos enable row level security;
      create policy empresa on empresas to authenticated using (true) with check (true);
      create policy perfil on perfis_usuarios to authenticated using (id=auth.uid()) with check (id=auth.uid());
      create policy orcamento on orcamentos to authenticated using (empresa_id in (select empresa_id from perfis_usuarios where id=auth.uid())) with check (empresa_id in (select empresa_id from perfis_usuarios where id=auth.uid()));
      grant select,insert,update,delete on all tables in schema public to authenticated;
    `);
    const templatesFix = fs.readFileSync(path.join(__dirname, '../database/projeto_templates_rls_fix.sql'), 'utf8');
    await db.exec(templatesFix);
    await db.exec(templatesFix);
    const pendencias = fs.readFileSync(path.join(__dirname, '../database/painel_rls_pendencias.sql'), 'utf8');
    await db.exec(pendencias);
    await db.exec(pendencias);
    await db.exec(`insert into tipologias values ('30000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001'),('30000000-0000-4000-8000-000000000002','${company}');
      insert into usuarios values ('${user}','${company}','vendedor');
      insert into medidas values (1);`);
    await db.exec(migration);
    // Instalação idempotente; o UID da proprietária não é recalculado por e-mail.
    await db.exec(migration);
    const financeiroSql = fs.readFileSync(path.join(__dirname, '../database/painel_financeiro.sql'), 'utf8');
    await db.exec(financeiroSql);
    await db.exec(financeiroSql);
    await db.exec(fs.readFileSync(path.join(__dirname, '../database/painel_historico_acessos.sql'), 'utf8'));
    const login = async id => db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false);`);
    await login(user);
    assert.equal((await db.query('select public.gc_proprietaria() ok')).rows[0].ok, false);
    await assert.rejects(db.query('select public.gc_painel()'), /exclusivo/);
    await assert.rejects(db.query(`select public.gc_alterar_acesso('empresa','${company}',true,'teste')`), /exclusivo/);
    await assert.rejects(db.query('select * from glasscode_private.proprietaria'), /permission denied/);
    assert.equal((await db.query('select * from orcamentos')).rows.length, 1);
    assert.deepEqual((await db.query('select id from projeto_templates')).rows, [{ id: 1 }]);
    await assert.rejects(db.query(`insert into projeto_templates values (4,'${company}')`), /row-level security/);
    assert.equal((await db.query('select * from tipologias')).rows.length, 1);
    for (const tabela of ['tipologias_ferragens','tipologias_perfis','tipologias_vidros']) {
      await assert.rejects(db.query(`insert into ${tabela} values ('40000000-0000-4000-8000-000000000001','30000000-0000-4000-8000-000000000001')`), /row-level security/);
      await db.query(`insert into ${tabela} values ('40000000-0000-4000-8000-000000000002','30000000-0000-4000-8000-000000000002')`);
    }
    assert.equal((await db.query("update usuarios set role='admin' returning id")).rows.length, 0);
    assert.equal((await db.query('select * from medidas')).rows.length, 0);
    await login(owner);
    assert.deepEqual((await db.query('select id from projeto_templates')).rows, [{ id: 2 }]);
    const painel = (await db.query('select public.gc_painel() painel')).rows[0].painel;
    assert.equal(painel.resumo.empresas, 2);
    await db.exec(`reset role; update auth.users set last_sign_in_at='2026-09-19T12:00:00Z' where id='${user}';`);
    await login(owner);
    let acessos=(await db.query('select public.gc_historico_acessos() resultado')).rows[0].resultado;
    assert.equal(acessos.eventos[0].email,'cliente@example.com');
    assert.equal(acessos.eventos[0].origem,'ultimo_login');
    await db.exec(`reset role; create table auth.audit_log_entries(id uuid primary key,payload jsonb,created_at timestamptz);
      insert into auth.audit_log_entries values ('50000000-0000-4000-8000-000000000001','{"actor_id":"${user}","actor_username":"cliente@example.com","action":"login"}','2026-09-19T12:00:01Z');`);
    await login(owner);
    acessos=(await db.query('select public.gc_historico_acessos() resultado')).rows[0].resultado;
    assert.equal(acessos.eventos.length,1);
    assert.equal(acessos.eventos[0].origem,'auditoria');
    assert.equal((await db.query("select public.gc_historico_acessos('inexistente') resultado")).rows[0].resultado.eventos.length,0);
    await login(user);
    await assert.rejects(db.query('select public.gc_historico_acessos()'), /exclusivo/);
    await login(owner);
    const alterarFinanceiro = async (acao, dados) => db.query('select public.gc_financeiro_alterar($1,$2::jsonb)', [acao, JSON.stringify(dados)]);
    await alterarFinanceiro('contrato', {empresa_id:company, plano:'Profissional', mensalidade_centavos:19990, dia_vencimento:10, motivo:'Contrato inicial'});
    await alterarFinanceiro('gerar', {empresa_id:company, competencia:'2020-01-01', motivo:'Lançamento janeiro'});
    await assert.rejects(alterarFinanceiro('gerar', {empresa_id:company, competencia:'2020-01-01', motivo:'Duplicado'}), /Já existe/);
    let financeiro=(await db.query('select public.gc_financeiro() painel')).rows[0].painel;
    const cobranca=financeiro.cobrancas[0];
    assert.equal(Number(financeiro.resumo.aberto),19990);
    assert.equal(cobranca.situacao,'atrasada');
    await alterarFinanceiro('contrato', {empresa_id:company, plano:'Novo plano', mensalidade_centavos:29990, dia_vencimento:15, motivo:'Mudança de plano'});
    assert.equal(Number((await db.query('select public.gc_financeiro() painel')).rows[0].painel.cobrancas[0].valor_centavos),19990);
    await assert.rejects(alterarFinanceiro('pagar', {id:cobranca.id, pago_em:'2099-01-01', motivo:'Data futura'}), /futuro/);
    await alterarFinanceiro('pagar', {id:cobranca.id, pago_em:'2020-01-10', motivo:'Extrato conferido'});
    await assert.rejects(alterarFinanceiro('pagar', {id:cobranca.id, pago_em:'2020-01-10', motivo:'Pagamento duplicado'}), /estado/);
    financeiro=(await db.query('select public.gc_financeiro() painel')).rows[0].painel;
    assert.equal(financeiro.cobrancas[0].status,'paga');
    assert.equal(Number(financeiro.resumo.aberto),0);
    await alterarFinanceiro('reabrir', {id:cobranca.id, motivo:'Correção do registro'});
    await alterarFinanceiro('cancelar', {id:cobranca.id, motivo:'Cancelamento conferido'});
    financeiro=(await db.query('select public.gc_financeiro() painel')).rows[0].painel;
    assert.equal(financeiro.cobrancas[0].status,'cancelada');
    assert.equal(financeiro.cobrancas[0].pago_em,null);
    assert.equal(financeiro.historico.length,6);
    await login(user);
    await assert.rejects(db.query('select public.gc_financeiro()'), /exclusivo/);
    await assert.rejects(alterarFinanceiro('contrato', {empresa_id:company,plano:'Ataque',motivo:'Sem permissão'}), /exclusivo/);
    await assert.rejects(db.query('select * from glasscode_private.cobrancas'), /permission denied/);
    await login(owner);
    await assert.rejects(db.query(`select public.gc_alterar_acesso('usuario','${owner}',true,'teste')`), /protegida/);
    await assert.rejects(db.query(`select public.gc_alterar_acesso('empresa','20000000-0000-4000-8000-000000000001',true,'teste')`), /protegida/);
    await assert.rejects(db.query(`select public.gc_alterar_acesso('empresa','${company}',true,'')`), /motivo/);
    await db.query(`select public.gc_alterar_acesso('empresa','${company}',true,'Suspensão de teste')`);
    await login(user);
    assert.equal((await db.query('select public.gc_acesso_permitido() ok')).rows[0].ok, false);
    assert.equal((await db.query('select * from orcamentos')).rows.length, 0);
    assert.equal((await db.query('select * from projeto_templates')).rows.length, 0);
    await assert.rejects(db.query(`insert into orcamentos values (2,'${company}')`), /row-level security/);
    // Tentar trocar a empresa enquanto bloqueado não altera o vínculo.
    assert.equal((await db.query(`update perfis_usuarios set empresa_id='20000000-0000-4000-8000-000000000001' where id='${user}' returning id`)).rows.length, 0);
    await login(owner);
    await db.query(`select public.gc_alterar_acesso('empresa','${company}',false,'Acesso restabelecido')`);
    await db.query(`select public.gc_alterar_acesso('usuario','${user}',true,'Bloqueio individual')`);
    await login(user);
    assert.equal((await db.query('select public.gc_acesso_permitido() ok')).rows[0].ok, false);
    await login(owner);
    await db.query(`select public.gc_alterar_acesso('usuario','${user}',false,'Acesso individual restabelecido')`);
    const final = (await db.query('select public.gc_painel() painel')).rows[0].painel;
    assert.equal(final.historico.length, 4);
    assert.ok(final.historico.every(e => e.autor_id === owner));
    await login(user);
    assert.equal((await db.query('select * from orcamentos')).rows.length, 1);
    await db.exec('reset role;');
    const situacoesSql=fs.readFileSync(path.join(__dirname,'../database/painel_situacao_contas.sql'),'utf8');
    await db.exec(situacoesSql);await db.exec(situacoesSql);
    await login(owner);
    const definir=async (tipo,id,situacao,categoria='outro',prazo=null)=>db.query('select public.gc_definir_situacao($1,$2,$3,$4,$5,$6,$7,$8)',[tipo,id,situacao,categoria,'NOTA_INTERNA_SECRETA','Mensagem pública de atendimento','suporte@example.com',prazo]);
    await definir('empresa',company,'pagamento_pendente','inadimplencia');
    assert.equal((await db.query('select public.gc_painel_situacoes() painel')).rows[0].painel.empresas.find(e=>e.id===company).situacao,'pagamento_pendente');
    await login(user);
    let minha=(await db.query('select public.gc_minha_situacao() s')).rows[0].s;
    assert.equal(minha.permitido,true);assert.equal(minha.situacao,'pagamento_pendente');
    assert.ok(!JSON.stringify(minha).includes('NOTA_INTERNA_SECRETA'));
    await assert.rejects(definir('empresa',company,'ativa'),/exclusivo/);
    await login(owner);
    await assert.rejects(definir('empresa',company,'regularizacao'),/prazo/);
    await assert.rejects(definir('usuario',owner,'suspensa_outro'),/protegida/);
    await definir('empresa',company,'regularizacao','inadimplencia','2099-01-01');
    await db.exec(`reset role; update glasscode_private.acessos set prazo='2020-01-01' where tipo='empresa' and alvo_id='${company}';`);
    await login(user);
    minha=(await db.query('select public.gc_minha_situacao() s')).rows[0].s;
    assert.equal(minha.permitido,true);assert.equal(minha.prazo_vencido,true);
    await login(owner);
    await definir('empresa',company,'suspensa_inadimplencia','inadimplencia');
    await definir('usuario',user,'pagamento_pendente','inadimplencia');
    await login(user);
    minha=(await db.query('select public.gc_minha_situacao() s')).rows[0].s;
    assert.equal(minha.permitido,false);assert.equal(minha.situacao,'suspensa_inadimplencia');
    assert.equal((await db.query('select * from orcamentos')).rows.length,0);
    await login(owner);await definir('empresa',company,'ativa');await definir('usuario',user,'cancelada','solicitacao_cliente');
    await login(user);assert.equal((await db.query('select public.gc_minha_situacao() s')).rows[0].s.situacao,'cancelada');
    await login(owner);await db.query(`select public.gc_alterar_acesso('usuario','${user}',false,'Liberação legada')`);
    await login(user);assert.equal((await db.query('select public.gc_minha_situacao() s')).rows[0].s.permitido,true);
    await db.exec('reset role; set role anon;');
    await assert.rejects(db.query('select public.gc_minha_situacao()'),/permission denied/);
    await assert.rejects(db.query('select public.gc_painel()'), /permission denied/);
  } finally { await db.close(); }
});
